version: '3.8'

services:
  jupyter:
    build: 
      context: ./jupyter
      dockerfile: Dockerfile
    volumes:
      - ./notebooks:/usr/src/app

  nginx:
    build: ./nginx
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - jupyter